### ISSUE TITLE
Export GPS data or GPX

### ISSUE THREAD

**Issue by ziiicos** [Fillius/PolarPersonalTrainerLib#2]
Hi, great work on this "private" API :)
I'm trying to adapt it to php, login and collecting activities between 2 dates are OK from now but I'd like to get more : GPS trace or GPX file for instance. Unfortunately I don't have the correct URL...any help ? How did you get this one for instance ?
https://www.polarpersonaltrainer.com/user/calendar/index.jxml?.action=export&.filename=export.xml&items.0.item=406490205&items.0.itemType=OptimizedExercise

I tried of course :
https://www.polarpersonaltrainer.com/user/calendar/index.jxml?.action=GPX&.filename=export.GPX&items.0.item=406490205&items.0.itemType=OptimizedExercise

but got 500 errors :( 

kind regards

(sorry I put this on issues, but I'm new in github and I don't know where to place my request (tried pull requests but no success :)

**Comment by Fillius** [comment]
Hi Ziiicos,

The 500 errors were indicating a hibernate session problem, I inspected a successful request in Chrome and saw it was using a different URL.

I have just had PPT give me a GPX file using (except I used a real Item ID):

https://www.polarpersonaltrainer.com/user/calendar/index.gpx?.action=gpx&.filename=export.gpx&items.0.item=00000000&items.0.itemType=OptimizedExercise

Good luck
